### PR TITLE
Added scroll-to callback. Updated README.

### PR DESCRIPTION
**Pull request by mciastek**

### CODE REVIEW

**Comment by jasonkriss** [comment]
@mciastek Thanks again for this. Couple notes... You can leave off the version bump. I'll take care of that. Also, I think you'll need to wrap the sendAction call in a function, right?

**Comment by mciastek** [comment]
@jasonkriss sendAction can be passed without surrounding function to jQuery.animate callback (tested it).

**Comment by jasonkriss** [comment]
sendAction is indeed a function but i think in this case you are actually passing the return value of the call to sendAction, instead of sendAction itself. Because of this, the callback is actually executing as soon as we call animate instead of when the animation has finished. Does that make sense?

**Comment by mciastek** [comment]
You are right! I've wrapped `this.sendAction()` into function and now it works like charm.

**Comment by jasonkriss** [comment]
Awesome! Thanks for making that change. Do you mind making the suggested simplification, removing the version bump, and squashing your commits? Thanks again for this @mciastek!

**Comment by mciastek** [comment]
Done.

**Comment by jasonkriss** [comment]
@mciastek Nice! Thanks again!

**Pull request merged**
