### PR TITLE
Ensures targets top is only offset by the scrollable's top when appropriate

### LINKED ISSUE #36: Pull Request #25 breaks ember-scroll-to on Chrome 61
Ember-scroll-to no longer works in chrome. 
The code added in PR #25 tries to normalize the targets offset top by the scrollable containers top (if the page is scrolled) and the scrollable containers current scroll position. This is necessary because the target's top is calculated from the top of the document, not its scrolling parent. 

Anyhow, we want to normalize the targets offset top only when necessary. 

Steps to reproduce, 
* clone the repo
* start up the dummy app in the latest version of chrome
* paste this code into the application.hbs, observe that it does not do what you expect.

```handlebars
<div style='position: fixed; top: 40px; right: 40px; color: black; background-color: lightGrey; padding: 5px;'>
  <h3 style='color: black;'>Scroll Nav Menu</h3>
  <div>
    {{#scroll-to href='body'}}
    Position TOP OF BODY
    {{/scroll-to}}
  </div>

  <div>
    {{#scroll-to href='#position-1'}}
    Position 1
    {{/scroll-to}}
  </div>

  <div>
    {{#scroll-to href='#position-2'}}
    Position 2
    {{/scroll-to}}
  </div>

  <div>
    {{#scroll-to href='#position-3'}}
    Position 3
    {{/scroll-to}}
  </div>
</div>

<div class='spacer' style='height: 400px;'>Spacer</div>
<div class='spacer' style='height: 400px;'>Spacer</div>
<div class='spacer' style='height: 400px;'>Spacer</div>

<div id='position-1' style='height: 400px; background-color: lime;'>
  Position 1 scroll destination
</div>

<div class='spacer' style='height: 400px;'>Spacer</div>
<div class='spacer' style='height: 400px;'>Spacer</div>
<div class='spacer' style='height: 400px;'>Spacer</div>

<div id='position-2' style='height: 400px; background-color: lime;'>
  Position 2 scroll destination
</div>

<div class='spacer' style='height: 400px;'>Spacer</div>
<div class='spacer' style='height: 400px;'>Spacer</div>
<div class='spacer' style='height: 400px;'>Spacer</div>

<div id='position-3' style='height: 400px; background-color: lime;'>
  Position 3 scroll destination
</div>

<div class='spacer' style='height: 400px;'>Spacer</div>
<div class='spacer' style='height: 400px;'>Spacer</div>
<div class='spacer' style='height: 400px;'>Spacer</div>
```

### PR DESCRIPTION
**Pull request by Duder-onomy**
Adds method to get the scrollableTop of the scrollable container from which to offset the targets top position, this method will only offset the targets top when the container's top is offset

Adds 2 new pages to the dummy app to demonstrate this lib and how it is
expected to work

Fixes #36
Patches PR #25

### CODE REVIEW

**Comment by Duder-onomy** [comment]
@ragnarpeterson Any interest in getting this merged? Do you want me to change anything?

**Comment by chvonrohr** [comment]
would really appreciate if this could be merged, as scroll-to position does not work at the moment in Chrome.

**Comment by Duder-onomy** [comment]
@blimmer ^ Any interest in getting this merged?

**Comment by blimmer** [comment]
Hey @Duder-onomy - I don't really work with Ember anymore. Have you guys had a chance to test this out to confirm it works? I can merge but I can't really confirm that it does the right thing / doesn't break other browsers, etc.

**Comment by chvonrohr** [comment]
I merged the PR for application and it works like a charm. Without, top-offset is calculated wrong in latest chrome.
Hope you're back soon in the ember community ;)

**Comment by blimmer** [comment]
Sounds good - I'll merge!

**Comment by Duder-onomy** [comment]
BOOM!

**Pull request merged**
